export const siteConfig = {
  name: "Kelven Souza",
  title: "Kelven Souza - Desenvolvedor Full-Stack",
  description: "Desenvolvedor Full-Stack especializado em React, Node.js e Python. Especialista em e-commerce (VTEX, Wake, Shopify) e soluções digitais modernas.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://simks.com.br",
  ogImage: "/logo.png",
  email: "kelven.souza00@gmail.com",
  location: "Alagoinhas, BA",
  social: {
    github: "https://github.com/SimksS",
    linkedin: "https://linkedin.com/in/kelvensouza",
  },
  keywords: [
    "desenvolvedor full-stack",
    "react",
    "node.js",
    "python",
    "vtex",
    "wake",
    "shopify",
    "e-commerce",
    "next.js",
    "typescript",
    "kelven souza",
    "desenvolvedor",
    "programador",
    "desenvolvimento web",
  ],
} as const;
